import Navbar from '@/components/Navbar'
import SideBar from '@/components/SideBar'
import { Metadata } from 'next';
import React, { ReactNode } from 'react'

export const metadata: Metadata = {
  title: "Video Calling APP || YOOM",
  description: "Generated by create next app",
  icons:{
    icon:'/icons/logo.svg'
  }
};

const HomeLayout = ({children}:{children:ReactNode}) => {
  return (
    <main className='relative  '>
        <Navbar/>
        <div className='flex h-[calc(100vh-32px)] '>
            <SideBar/>
            <section className='flex flex-1 h-[calc(100vh-32px)] overflow-y-auto flex-col px-6 pb-6 pt-28 max-md:pb-14 sm:px-14'>
                <div className='w-full'>
                    {children}
                </div>
            </section>
        </div>
        Footer
    </main>
  )
}

export default HomeLayout